### ISSUE TITLE
Example for runtime dynamic dispatch?

### ISSUE THREAD

**Issue by jerinphilip** [mozilla/gemmology#10]
Hi, thanks for the rewrite. 

I see [xsimd](https://github.com/xtensor-stack/xsimd) already available in distributions and am looking at gemmology to enable the ability to distribute an alternate, slightly wieldier frontend to bergamot-translator.

Could you provide an example of the dynamic dispatch at runtime mentioned in the [README](https://github.com/mozilla/gemmology/tree/master#difference-with-intgemm)?

I'm looking at [dispatch docs](https://xsimd.readthedocs.io/en/latest/api/dispatching.html). Our current use of gemmology can be found [here](https://github.com/jerinphilip/slimt/blob/9920fbd2d5b0759b436a3c7b4642d3c09454f22f/slimt/QMM.cc#L540-L778) - it appears to be working on my `x86_64` and a friend's (cc @georg3tom) `aarch64`.

I find functions in [gemmology.h](https://github.com/mozilla/gemmology/blob/master/gemmology.h), while the [dynamic dispatch docs](https://xsimd.readthedocs.io/en/latest/api/dispatching.html) seem to require a functor (`sum{}`).

```cpp
// Create the dispatching function, specifying the architecture we want to
// target.
auto dispatched = xsimd::dispatch<xsimd::arch_list<xsimd::avx2, xsimd::sse2>>(sum{});
``` 

Is the recommendation to create these for all functions I use? If it's not too much, can you provide me a skeleton for one, I should be able to replicate it for the others.

Further advice and alternate suggestions are much appreciated, thank you. 

Edit: 

1. I am able to find breadcrumbs on https://github.com/mozilla/gecko-dev/commit/1b97818ea7994f3c43615dd931bfee260cedca70 and https://github.com/mozilla/gecko-dev/commit/29fb09d2f17e4296af7e35a491c7781a71418aa1. 
2. I have pulled dispatch based on the example in gecko-dev and am currently getting incorrect outputs. https://github.com/jerinphilip/slimt/pull/17
3. I fixed 2 with https://github.com/jerinphilip/slimt/pull/17/commits/cda9d8c4132892bc78247e8bb0aa85e26c77b0c3. 

Leaving the issue open, in case you want to add something.

**Comment by serge-sans-paille** [comment]
Hey, thanks for using gemmology. Yeah, as you spotted, the dispatch mechanism is already used in firefox and you have an example in https://github.com/mozilla/gecko-dev/commit/1b97818ea7994f3c43615dd931bfee260cedca70#diff-0ed5ba8eb394d9906aaaa6c3a789b11bdd6578be87b6d7194e5c879170d48ae4R38
